version: '3.8'

services:
  llm-server:
    image: ollama/ollama:latest
    container_name: llm-server
    ports:
      - "11434:11434"
    volumes:
      - /opt/ollama/data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    command: serve
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - /opt/redis/data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres-server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mcp_chat
      - POSTGRES_USER=mcp_user
      - POSTGRES_PASSWORD=mcp_password
    volumes:
      - /opt/postgres/data:/var/lib/postgresql/data
      - /opt/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  ollama_data:
  redis_data:
  postgres_data:
