version: '3.8'

services:
  llm-server:
    image: ollama/ollama:latest
    container_name: llm-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    command: serve
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  web-app:
    build: .
    container_name: web-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - OLLAMA_BASE_URL=http://llm-server:11434
      - REDIS_URL=redis://redis-server:6379
    depends_on:
      - llm-server
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  ollama_data:
  redis_data:
